import Foundation
import GenaryxCoreFFI
import Observation

/// Live fleet state for the shell: constructs the real `genaryx-core`
/// through the UniFFI bridge (`GenaryxCoreFFI`, generated by
/// `build-ffi.sh`), seeds from stored history, then keeps growing from live
/// pushes. Replaces the Phase-0 `MockData` array.
///
/// `FleetHandle()` seeds its own throwaway demo world and runs its own
/// ingest + feeder threads internally (see `crates/ffi/README.md`), so this
/// model does no polling of its own: it seeds once from `recentEvents` and
/// reacts to `EventListener` pushes for everything after that.
@MainActor
@Observable
final class FleetModel {
    /// Newest-first, capped at `capacity`. Seeded from `recentEvents`, then
    /// grown by live pushes via `prepend`.
    private(set) var events: [UiEvent] = []

    /// Set when `FleetHandle()` construction throws. `events` stays empty
    /// and the shell shows this instead of crashing: fail-closed, matching
    /// crates/ffi's own "nothing panics across FFI" contract.
    private(set) var unavailableMessage: String?

    private static let capacity = 500

    /// Kept alive for the model's lifetime: dropping it would tear down the
    /// demo world and stop the ingest/feeder threads (see `FleetHandle`'s
    /// `Drop` impl).
    private var handle: FleetHandle?
    /// Kept alive alongside `handle` for clarity of ownership, even though
    /// UniFFI's callback-interface handle map also holds a strong reference
    /// on the Swift side for as long as Rust needs it.
    private var listener: FleetEventListener?

    /// Fired synchronously, on the main actor, immediately after a new
    /// live-pushed event is prepended - the one choke point every live
    /// event already passes through. `GenaryxApp` wires this once at launch
    /// so `ApprovalNotificationModel` (docs/PHASE2.md Wave 3, "actionable
    /// notifications") can watch "the SAME FleetModel bus events the
    /// Decision Stream already filters" event-by-event, instead of polling
    /// `events` on a timer. Not fired for the initial `recentEvents` seed in
    /// `init()` - PHASE2.md only asks for a notification when a fresh
    /// `approval_requested` "arrives", never a backlog replay on launch.
    var onNewEvent: ((UiEvent) -> Void)?

    init() {
        do {
            let handle = try FleetHandle()
            let seeded = try handle.recentEvents(limit: UInt32(Self.capacity))
            let listener = FleetEventListener(model: self)
            handle.subscribe(listener: listener)

            self.handle = handle
            self.listener = listener
            self.events = seeded
        } catch let error as FfiError {
            switch error {
            case .Core(let msg):
                self.unavailableMessage = msg
            }
        } catch {
            self.unavailableMessage = String(describing: error)
        }
    }

    /// Adds one live-pushed event to the front of the list and re-caps.
    /// Only ever called on the main actor: `FleetEventListener` hops here
    /// before calling in, since `onEvent` itself fires on a Rust thread.
    func prepend(_ event: UiEvent) {
        events.insert(event, at: 0)
        if events.count > Self.capacity {
            events.removeLast(events.count - Self.capacity)
        }
        onNewEvent?(event)
    }

    // MARK: - delegation graph + Agent 360 (PHASE3 W3)
    //
    // `FleetHandle` owns these three reads too: the delegation graph is
    // core's own bus-fed graph (built from the SAME Store this model already
    // seeded from), not Idryx's - see `crates/ffi/src/lib.rs`'s module doc.
    // So `GraphModel`/`Agent360Model` call through THIS model's already-live
    // `handle` rather than opening a second `FleetHandle` of their own
    // (which would seed an independent throwaway demo world with its own
    // ingest/feeder threads - wasteful, and not the same data this model's
    // `events` already show). Every call runs inside `Task.detached`, off
    // this model's `@MainActor` isolation, exactly like
    // `CloudModel`/`PolicyModel`/`IdentityModel` wrap their own handles (see
    // `CloudModel.swift`'s doc for the full rationale); only the
    // already-resolved result is awaited back onto the main actor.

    /// `handle`, or an honest `FfiError` when construction itself failed
    /// (see `unavailableMessage`) - never a silent empty result, since
    /// unlike a real read this is "the call could not even be attempted."
    private func requireHandle() throws -> FleetHandle {
        guard let handle else {
            throw FfiError.Core(msg: unavailableMessage ?? "fleet handle unavailable")
        }
        return handle
    }

    /// The whole delegation graph, laid out for the Graph tab's Canvas2D
    /// renderer (PHASE3.md position 3: layout computed once in core).
    func agentGraph() async throws -> LayoutViewRecord {
        let handle = try requireHandle()
        return try await Task.detached { try handle.agentGraph() }.value
    }

    /// One agent's immediate delegation neighborhood, for Agent 360's
    /// Delegation section.
    func agentSlice(_ agentId: String) async throws -> AgentSliceRecord {
        let handle = try requireHandle()
        return try await Task.detached { try handle.agentSlice(agentId: agentId) }.value
    }

    /// This agent's own recent events, for Agent 360's Events section.
    func eventsForAgent(_ agentId: String, limit: UInt32) async throws -> [UiEvent] {
        let handle = try requireHandle()
        return try await Task.detached { try handle.eventsForAgent(agentId: agentId, limit: limit) }.value
    }
}

/// Bridges `EventListener.onEvent` (called from the Rust ingest thread,
/// never the main thread; see `crates/ffi/README.md`) to `FleetModel` on
/// the main actor.
///
/// `@unchecked Sendable` because the generated `EventListener` protocol
/// requires `Sendable` (mirroring the Rust trait's `Send + Sync` bound),
/// and this class's only stored state is a `weak` back-reference to a
/// `@MainActor`-isolated, non-Sendable model. That reference is never read
/// for anything other than scheduling a hop: `onEvent` does not touch any
/// model state itself, it only captures `model` weakly into a
/// `Task { @MainActor in ... }`, so all actual state mutation happens after
/// isolation is established, never concurrently with it.
final class FleetEventListener: EventListener, @unchecked Sendable {
    private weak var model: FleetModel?

    init(model: FleetModel) {
        self.model = model
    }

    func onEvent(event: UiEvent) {
        Task { @MainActor [weak model] in
            model?.prepend(event)
        }
    }
}
