import Foundation
import GenaryxCoreFFI
import Observation

/// Live fleet state for the shell: constructs the real `genaryx-core`
/// through the UniFFI bridge (`GenaryxCoreFFI`, generated by
/// `build-ffi.sh`), seeds from stored history, then keeps growing from live
/// pushes. Replaces the Phase-0 `MockData` array.
///
/// `FleetHandle()` seeds its own throwaway demo world and runs its own
/// ingest + feeder threads internally (see `crates/ffi/README.md`), so this
/// model does no polling of its own: it seeds once from `recentEvents` and
/// reacts to `EventListener` pushes for everything after that.
@MainActor
@Observable
final class FleetModel {
    /// Newest-first, capped at `capacity`. Seeded from `recentEvents`, then
    /// grown by live pushes via `prepend`.
    private(set) var events: [UiEvent] = []

    /// Set when `FleetHandle()` construction throws. `events` stays empty
    /// and the shell shows this instead of crashing: fail-closed, matching
    /// crates/ffi's own "nothing panics across FFI" contract.
    private(set) var unavailableMessage: String?

    private static let capacity = 500

    /// Kept alive for the model's lifetime: dropping it would tear down the
    /// demo world and stop the ingest/feeder threads (see `FleetHandle`'s
    /// `Drop` impl).
    private var handle: FleetHandle?
    /// Kept alive alongside `handle` for clarity of ownership, even though
    /// UniFFI's callback-interface handle map also holds a strong reference
    /// on the Swift side for as long as Rust needs it.
    private var listener: FleetEventListener?

    init() {
        do {
            let handle = try FleetHandle()
            let seeded = try handle.recentEvents(limit: UInt32(Self.capacity))
            let listener = FleetEventListener(model: self)
            handle.subscribe(listener: listener)

            self.handle = handle
            self.listener = listener
            self.events = seeded
        } catch let error as FfiError {
            switch error {
            case .Core(let msg):
                self.unavailableMessage = msg
            }
        } catch {
            self.unavailableMessage = String(describing: error)
        }
    }

    /// Adds one live-pushed event to the front of the list and re-caps.
    /// Only ever called on the main actor: `FleetEventListener` hops here
    /// before calling in, since `onEvent` itself fires on a Rust thread.
    func prepend(_ event: UiEvent) {
        events.insert(event, at: 0)
        if events.count > Self.capacity {
            events.removeLast(events.count - Self.capacity)
        }
    }
}

/// Bridges `EventListener.onEvent` (called from the Rust ingest thread,
/// never the main thread; see `crates/ffi/README.md`) to `FleetModel` on
/// the main actor.
///
/// `@unchecked Sendable` because the generated `EventListener` protocol
/// requires `Sendable` (mirroring the Rust trait's `Send + Sync` bound),
/// and this class's only stored state is a `weak` back-reference to a
/// `@MainActor`-isolated, non-Sendable model. That reference is never read
/// for anything other than scheduling a hop: `onEvent` does not touch any
/// model state itself, it only captures `model` weakly into a
/// `Task { @MainActor in ... }`, so all actual state mutation happens after
/// isolation is established, never concurrently with it.
final class FleetEventListener: EventListener, @unchecked Sendable {
    private weak var model: FleetModel?

    init(model: FleetModel) {
        self.model = model
    }

    func onEvent(event: UiEvent) {
        Task { @MainActor [weak model] in
            model?.prepend(event)
        }
    }
}
