import AppKit
import GenaryxCoreFFI
import SwiftUI

/// Genaryx: the native macOS SwiftUI shell (decision D2) over `genaryx-core`.
///
/// `FleetModel` constructs the real `FleetHandle` through the UniFFI bridge
/// (`GenaryxCoreFFI`, generated by `build-ffi.sh` from `crates/ffi`) and
/// feeds both the main window and the menu-bar view from one live,
/// appending event stream, replacing the Phase-0 `MockData` array.
///
/// Phase-1 wave 3 (docs/PHASE1.md) adds `CloudModel`, the same kind of
/// UniFFI-backed live model but over `CloudHandle` (`crates/ffi/src/cloud`)
/// instead of `FleetHandle`, feeding the new Overview and Money panels
/// alongside the existing Bus Explorer via `TabBar` below - at parity with
/// the Tauri shell's three-view `AppHeader.tsx`/`AppShell.tsx` switcher.
///
/// Phase-2 wave 2 (docs/PHASE2.md) adds `PolicyModel`, the same kind of
/// UniFFI-backed live model but over `WardryxHandle`
/// (`crates/ffi/src/wardryx`), feeding the new Policy panel (Decision
/// Stream, Approvals Inbox, Policy view). Its Decision Stream section reads
/// `model.events` (the existing `FleetModel` bus feed) directly, filtered to
/// `source == "wardryx"` - PHASE2.md: "NOT a new REST read" - so `PolicyView`
/// is handed `model.events` alongside its own `policyModel`.
///
/// Phase-2 wave 3 adds `notifications` (`ApprovalNotificationModel`) and the
/// `Posture` tab. `notifications` is wired to `model.onNewEvent` exactly
/// once below (`wireNotifications()`) so it sees every live bus event as it
/// arrives, the same feed `PolicyView`'s Decision Stream filters - never a
/// separate read. When a notification response comes back (Review / Approve
/// / Deny, or a plain tap), `notifications.focusRequest` changes; this
/// struct reacts by switching to the Policy tab and handing the target
/// approval id down as `focusedApprovalId`, which `PolicyView` uses to
/// scroll to and highlight that one row - PHASE2.md: "DEEP-LINKS... never
/// bypassed". `Posture` is fed straight from the three existing live models
/// (`cloudModel`, `policyModel`, `model`); it owns no handle and issues no
/// read of its own (see `PostureModel.swift`).
///
/// Phase-3 wave 2 (docs/PHASE3.md) adds `identityModel` (`IdentityModel`,
/// over `IdryxHandle`) and the `Identity` tab - identities list, the
/// 21-detector alert stream, Attestation. Read-only, so unlike `policyModel`
/// it needs no wiring into `notifications`/`focusedApprovalId` at all: there
/// is no privileged decision on this panel for a notification to deep-link
/// into this wave (W3's Agent 360 is where a cross-panel click-through
/// lands).
///
/// Phase-3 wave 3 adds `graphModel` (`GraphModel`, over `FleetModel`'s own
/// `agentGraph()`) and the `Graph` tab - the delegation graph, drawn from
/// core's laid-out positions. It also adds `agentFocus`: the Agent 360
/// deep-link target, wired from a delegation-graph node tap
/// (`DelegationGraphView`) and an Identity row tap (`IdentityView`) alike -
/// PHASE3.md's exit gate: "a click on any agent, from anywhere, opens a
/// full cross-plane Agent 360 card." Setting `agentFocus` presents
/// `Agent360View` as a sheet over whichever tab is currently showing,
/// mirroring `focusedApprovalId`'s own "a deep-link is just a piece of
/// state another view reacts to" shape from Phase-2 wave 3, just routed to
/// a sheet instead of an in-panel scroll+highlight (Agent 360 has no one
/// natural host panel to scroll within - it spans five).
///
/// Phase-3 wave 4 adds `replayModel` (`RunReplayModel`, over `FleetModel`'s
/// own `eventsForRun()`) and the `Replay` tab - a run's timeline, played
/// back with a scrub/speed clock (PHASE3.md position 5). `replayModel` is
/// owned here (not inside `RunReplayView`, unlike `Agent360Model`'s
/// per-sheet lifetime) so a playback position survives switching to
/// another tab and back, mirroring `graphModel`'s own precedent rather than
/// `agentFocus`'s. `focusedRunId` is the Replay analogue of
/// `focusedApprovalId`: a run row in the Money panel's `RunsTable` or in
/// Agent 360's Money section sets it (`openReplay(_:)` below) and switches
/// `tab` to `.replay` in the same step, exactly the established "a deep
/// link is just a piece of state another view reacts to" idiom - chosen
/// over presenting Replay as ANOTHER sheet (the task brief allows either)
/// because the scrub timeline benefits from full tab real estate the way
/// Agent 360's already-a-sheet card does not, and because Agent 360 is
/// already a sheet - a sheet launching a second sheet is exactly the
/// friction this idiom was introduced in Phase-2 wave 3 to avoid.
///
/// Phase-4 wave 1 (docs/PHASE4.md W1) adds `qualityModel` (`QualityModel`,
/// over `QualityHandle`) and `cryptoModel` (`CryptoModel`, over
/// `CryptoHandle`), plus the `Quality` and `Crypto` tabs - continuing the
/// per-plane-panel sequence right after `Identity`. Both are read-only, like
/// `identityModel`, so neither needs wiring into `notifications`/
/// `focusedApprovalId`. `QualityView` additionally takes `model.events` (the
/// same `FleetModel` bus feed `PolicyView`'s Decision Stream already
/// filters) for its live Drift Alerts section - Verdryx's `quality_drift`
/// event, not a new read through `QualityHandle` (see `QualityView.swift`'s
/// own doc). `CryptoView` takes no bus feed at all: Qryx has no live signal
/// of its own, every read is an explicit on-demand scan.
///
/// Phase-4 wave 2 (docs/PHASE4.md W2) adds `memoryModel` (`MemoryModel`, over
/// `MemoryHandle`) and `drillsModel` (`DrillsModel`, over `DrillsHandle`),
/// plus the `Memory` and `Drills` tabs - right after `Crypto`, continuing the
/// same per-plane-panel sequence. Both are read-only in the mutation sense
/// Money/Policy are (no journal, no Touch ID gate) - `MemoryView`'s one
/// `forget` action is a plain guarded confirm, not a break-glass override -
/// so neither needs wiring into `notifications`/`focusedApprovalId` either.
/// `MemoryView` additionally takes `model.events` (the same `FleetModel` bus
/// feed `QualityView`'s Drift Alerts and `PolicyView`'s Decision Stream
/// already filter) for its live Timeline section - every `engram.*` event,
/// not a new read through `MemoryHandle` (see `MemoryView.swift`'s own doc).
/// `DrillsView` takes no bus feed at all: mockryx has no live signal of its
/// own, every read is an explicit on-demand run.
///
/// Phase-4 wave 3 (docs/PHASE4.md W3) adds `evidenceModel` (`EvidenceModel`)
/// and the `Evidence` tab, right after `Drills` - the last of the per-plane
/// panels before the cross-cutting views (Graph/Replay/Posture/Bus
/// Explorer). Unlike every other Phase-4 model, `EvidenceModel` owns no
/// handle of its own: `EvidenceView` is handed `cloudModel` directly
/// alongside `evidenceModel`, exactly how `PostureView` already receives
/// `cloudModel` - the Evidence Center builds through the SAME paired
/// `CloudHandle` Money/Overview use (`CloudModel.cloudHandle`), never a
/// second device pairing.
///
/// Phase-4 wave 4 (docs/PHASE4.md W4, decision D11) adds `remoteModel`
/// (`RemoteModel`, over `RemoteHandle`) and the `Remote` tab, right after
/// `Evidence` - continuing the same per-plane-panel sequence one more time
/// before the cross-cutting views. `RemoteView` manages the TRANSPORT to a
/// client-hosted stack (Hetzner read-only inventory, the WireGuard tunnel,
/// host-key-pinned SSH ops), not the stack itself - no other tab re-points
/// through it. Read-only in the mutation sense Money/Policy are (Hetzner
/// never mutates; the tunnel Connect/Disconnect and SSH ops are local
/// transport actions, not remote governance decisions), so like
/// `identityModel`/`cryptoModel` it needs no wiring into
/// `notifications`/`focusedApprovalId` either.
///
/// Phase-5 wave 2 (docs/PHASE5.md W2, itrat-console/13 D12.2a) adds
/// `pocketModel` (`PocketModel`, over `PocketHandle`) and the `Pocket` tab,
/// right after `Remote` - continuing the same per-plane-panel sequence.
/// "Connect TokenFuse Pocket" mints a pairing code, arms the relay's pairing
/// window, and renders the QR the phone scans; unlike `remoteModel` it holds
/// no long-lived connection of its own (no keypair, no tunnel) - every
/// method resolves the Cloud admin key and the relay admin URL fresh, per
/// call (see `PocketModel.swift`'s own doc). Read/act-only in the local
/// transport sense Remote is (pairing/disconnect are local transport
/// actions, not remote governance decisions), so like `remoteModel` it needs
/// no wiring into `notifications`/`focusedApprovalId` either.
@main
struct GenaryxApp: App {
    @State private var model = FleetModel()
    @State private var cloudModel = CloudModel()
    @State private var policyModel = PolicyModel()
    @State private var identityModel = IdentityModel()
    @State private var qualityModel = QualityModel()
    @State private var cryptoModel = CryptoModel()
    @State private var memoryModel = MemoryModel()
    @State private var drillsModel = DrillsModel()
    @State private var evidenceModel = EvidenceModel()
    @State private var remoteModel = RemoteModel()
    @State private var pocketModel = PocketModel()
    @State private var graphModel = GraphModel()
    @State private var replayModel = RunReplayModel()
    @State private var notifications = ApprovalNotificationModel()
    @State private var tab: AppTab = .overview
    /// The approval to scroll to and highlight once `tab` is `.policy` -
    /// see the type doc's "Phase-2 wave 3" paragraph.
    @State private var focusedApprovalId: String?
    /// The agent whose Agent 360 card is currently presented as a sheet -
    /// see the type doc's "Phase-3 wave 3" paragraph. `nil` means no sheet.
    @State private var agentFocus: AgentFocus?
    /// The run id to load once `tab` is `.replay` - see the type doc's
    /// "Phase-3 wave 4" paragraph.
    @State private var focusedRunId: String?

    var body: some Scene {
        WindowGroup("Genaryx") {
            VStack(spacing: 0) {
                TabBar(tab: $tab)
                Divider().overlay(Theme.hairline)
                Group {
                    switch tab {
                    case .overview:
                        OverviewView(model: cloudModel, onOpenAgent: { agentFocus = AgentFocus(agentId: $0) })
                    case .money:
                        MoneyView(
                            model: cloudModel, onOpenReplay: openReplay,
                            onOpenAgent: { agentFocus = AgentFocus(agentId: $0) })
                    case .policy:
                        PolicyView(
                            model: policyModel, busEvents: model.events, notifications: notifications,
                            focusedApprovalId: focusedApprovalId)
                    case .identity:
                        IdentityView(model: identityModel, onOpenAgent: { agentFocus = AgentFocus(agentId: $0) })
                    case .quality:
                        QualityView(model: qualityModel, busEvents: model.events)
                    case .crypto:
                        CryptoView(model: cryptoModel)
                    case .memory:
                        MemoryView(model: memoryModel, busEvents: model.events)
                    case .drills:
                        DrillsView(model: drillsModel)
                    case .evidence:
                        EvidenceView(model: evidenceModel, cloudModel: cloudModel)
                    case .remote:
                        RemoteView(model: remoteModel)
                    case .pocket:
                        PocketView(model: pocketModel)
                    case .graph:
                        DelegationGraphView(
                            fleetModel: model, model: graphModel,
                            onOpenAgent: { agentFocus = AgentFocus(agentId: $0) })
                    case .replay:
                        RunReplayView(fleetModel: model, model: replayModel, focusedRunId: focusedRunId)
                    case .posture:
                        PostureView(
                            cloudModel: cloudModel, policyModel: policyModel, identityModel: identityModel,
                            fleetModel: model)
                    case .bus:
                        VStack(spacing: 0) {
                            if let message = model.unavailableMessage {
                                CoreUnavailableBanner(message: message)
                            }
                            BusExplorerView(events: model.events)
                        }
                    }
                }
            }
            .frame(minWidth: 1120, minHeight: 640)
            .sheet(item: $agentFocus) { focus in
                Agent360View(
                    agentId: focus.agentId, fleetModel: model, cloudModel: cloudModel, policyModel: policyModel,
                    identityModel: identityModel,
                    onClose: { agentFocus = nil },
                    onOpenMoney: {
                        tab = .money
                        agentFocus = nil
                    },
                    onOpenPolicy: {
                        tab = .policy
                        agentFocus = nil
                    },
                    onOpenReplay: openReplay
                )
            }
            .task {
                wireNotifications()
            }
            .onChange(of: notifications.focusRequest) { _, newValue in
                guard let newValue else { return }
                tab = .policy
                focusedApprovalId = newValue.approvalId
                notifications.clearFocusRequest()
            }
            .onChange(of: tab) { _, newTab in
                // Clear the highlight/focus once the operator navigates away
                // from its own tab themselves, rather than on a timer -
                // simple, deterministic, no race with `ScrollViewReader`'s
                // own one-shot `scrollTo` in `PolicyView`.
                if newTab != .policy {
                    focusedApprovalId = nil
                }
                if newTab != .replay {
                    focusedRunId = nil
                }
            }
        }

        MenuBarExtra {
            MenuBarBusView(events: model.events, unavailableMessage: model.unavailableMessage, cloudModel: cloudModel)
        } label: {
            MenuBarLabel(count: model.events.count, cloudModel: cloudModel)
        }
        .menuBarExtraStyle(.window)
    }

    /// One-time wiring between `FleetModel`'s live event hook and
    /// `notifications` - guarded so re-running this `.task` (e.g. a second
    /// window) never double-attaches the closure. `environmentLabel` is
    /// computed fresh on EVERY event rather than captured once, so a
    /// (currently hypothetical) later reconnect is reflected immediately
    /// rather than muting/notifying against a stale environment string.
    private func wireNotifications() {
        guard model.onNewEvent == nil else { return }
        model.onNewEvent = { [policyModel, notifications] event in
            notifications.handle(
                event: event, environment: ApprovalNotificationModel.environmentLabel(for: policyModel.connection))
        }
    }

    /// The Run Replay deep-link entry point (PHASE3 W4): switches to the
    /// `Replay` tab focused on `runId` and, if Agent 360 happened to be the
    /// sheet a "Replay" link was tapped from, dismisses it - the exact same
    /// two-step `onOpenMoney`/`onOpenPolicy` already perform, just landing
    /// on `.replay` instead. Passed to both `MoneyView` (whose `RunsTable`
    /// rows link out per PHASE3.md's "a run row") and `Agent360View` (whose
    /// Money section rows do the same).
    private func openReplay(_ runId: String) {
        tab = .replay
        focusedRunId = runId
        agentFocus = nil
    }
}

/// The Agent 360 deep-link target (PHASE3 W3): `.sheet(item:)` needs
/// `Identifiable`, and an agent id is already a stable, unique identifier -
/// no separate UUID needed. Two agent-id-equal requests collapse to the
/// SAME sheet identity, so re-tapping the already-open agent (from a second
/// entry point) does not flicker the sheet closed and immediately reopened.
private struct AgentFocus: Identifiable, Equatable {
    let agentId: String
    var id: String { agentId }
}

/// The fifteen top-level nav destinations - Overview, Money, Policy,
/// Identity, Quality, Crypto, Memory, Drills, Evidence, Remote, Pocket,
/// Graph, Replay, Posture, and the existing Bus Explorer - matching the
/// Tauri shell's `ViewId`/`lib/views.ts` switcher (extended with Memory +
/// Drills in Phase-4 wave 2, then Evidence in Phase-4 wave 3, then Remote in
/// Phase-4 wave 4, then Pocket in Phase-5 wave 2, mirroring wave 1's Quality
/// + Crypto addition), rendered as a native macOS tab strip instead of a
/// web-styled nav bar (native macOS patterns over pixel parity, same rule
/// `Theme.swift` already follows). Memory, Drills, Evidence, Remote, and
/// Pocket sit right after Crypto, continuing the per-plane-panel sequence
/// (Money/Policy/Identity/Quality/Crypto/Memory/Drills/Evidence/Remote/Pocket)
/// ahead of the cross-cutting views (Graph/Replay/Posture/Bus Explorer).
private enum AppTab: String, CaseIterable, Identifiable {
    case overview = "Overview"
    case money = "Money"
    case policy = "Policy"
    case identity = "Identity"
    case quality = "Quality"
    case crypto = "Crypto"
    case memory = "Memory"
    case drills = "Drills"
    case evidence = "Evidence"
    case remote = "Remote"
    case pocket = "Pocket"
    case graph = "Graph"
    case replay = "Replay"
    case posture = "Posture"
    case bus = "Bus Explorer"

    var id: String { rawValue }
}

/// Persistent app chrome above whichever tab is active: brand mark plus the
/// view switcher. Mirrors `AppHeader.tsx`'s role (shown once regardless of
/// which view is active) without reproducing its web-specific theme toggle
/// (this shell already follows the system light/dark appearance - see
/// `Color.dynamic` in `Theme.swift`).
@MainActor
private struct TabBar: View {
    @Binding var tab: AppTab

    var body: some View {
        HStack(spacing: 14) {
            HStack(spacing: 8) {
                Image(systemName: "bolt.fill")
                    .font(.system(size: 13, weight: .bold))
                    .foregroundStyle(Theme.amber)
                VStack(alignment: .leading, spacing: 1) {
                    Text("Genaryx")
                        .font(Theme.display(13, weight: .bold))
                        .foregroundStyle(Theme.textPrimary)
                    Text("CONTROL ROOM")
                        .font(Theme.mono(9, weight: .semibold))
                        .tracking(1.4)
                        .foregroundStyle(Theme.textTertiary)
                }
            }

            HStack(spacing: 2) {
                ForEach(AppTab.allCases) { item in
                    Button {
                        tab = item
                    } label: {
                        Text(item.rawValue)
                            .font(Theme.mono(11.5, weight: .semibold))
                            .lineLimit(1)
                            .fixedSize(horizontal: true, vertical: false)
                            .foregroundStyle(tab == item ? Theme.textPrimary : Theme.textSecondary)
                            .padding(.horizontal, 11)
                            .padding(.vertical, 6)
                            .background(
                                RoundedRectangle(cornerRadius: 8, style: .continuous)
                                    .fill(tab == item ? Theme.panelElevated : Color.clear)
                            )
                            .overlay(
                                RoundedRectangle(cornerRadius: 8, style: .continuous)
                                    .strokeBorder(tab == item ? Theme.hairlineStrong : Color.clear, lineWidth: 1)
                            )
                    }
                    .buttonStyle(.plain)
                }
            }
            .padding(.leading, 4)

            Spacer(minLength: 0)
        }
        .padding(.horizontal, 16)
        .padding(.vertical, 10)
        .background(Theme.panel)
    }
}

/// Shown above the Bus Explorer only when `FleetHandle()` failed to
/// construct. Fail-closed: the shell still launches and renders (with an
/// empty list) instead of crashing.
@MainActor
private struct CoreUnavailableBanner: View {
    let message: String

    var body: some View {
        HStack(spacing: 8) {
            Image(systemName: "exclamationmark.triangle.fill")
                .foregroundStyle(Theme.ember)
            Text("Core unavailable: \(message)")
                .font(Theme.mono(11, weight: .semibold))
                .foregroundStyle(Theme.textSecondary)
                .lineLimit(1)
                .truncationMode(.tail)
            Spacer(minLength: 0)
        }
        .padding(.horizontal, 16)
        .padding(.vertical, 8)
        .background(Theme.panelElevated)
    }
}

/// The `NSStatusItem` label: a small glyph plus the live event count (kept
/// exactly as before - terse, since the status bar has very little
/// horizontal room), plus a compact burn figure from `CloudModel` (Phase-1
/// wave 5, docs/PHASE1.md; 08 §2, 09 Ф1 upstream) alongside it.
@MainActor
private struct MenuBarLabel: View {
    let count: Int
    let cloudModel: CloudModel

    var body: some View {
        HStack(spacing: 6) {
            Label {
                Text("\(count)")
                    .monospacedDigit()
            } icon: {
                Image(systemName: "waveform.path.ecg")
            }
            if let burnText {
                Text(burnText)
                    .monospacedDigit()
            }
        }
    }

    /// `nil` until `CloudModel` has a real reading (still connecting, no
    /// environment, pairing failed), so the always-visible status item never
    /// shows a fabricated or stale-looking number - fail-closed: absent
    /// beats wrong. Once `CloudModel.overview` has a value, this keeps
    /// showing it even through a later transient refresh error, the same
    /// "last known good over blank" posture `MoneyView`/`OverviewView`
    /// already take with their own `model.overview`/`model.runs`.
    private var burnText: String? {
        guard let overview = cloudModel.overview else { return nil }
        return MoneyFormat.usd(overview.totalSpentUsd)
    }
}

/// The MenuBarExtra's popover content: a condensed, read-only slice of the
/// bus feed, so a quick glance never requires opening the main window - plus
/// (Phase-1 wave 5) the Money section right below the header: a burn
/// readout and a "kill last runaway" action over the same `CloudModel` the
/// Overview/Money tabs use, so the mini never issues its own Cloud calls.
@MainActor
private struct MenuBarBusView: View {
    let events: [UiEvent]
    let unavailableMessage: String?
    let cloudModel: CloudModel

    private static let previewCount = 8
    /// Matches `OverviewView`/`MoneyView`'s own refresh cadence, so the mini
    /// never looks "more live" or "more stale" than the panel it mirrors.
    private static let refreshInterval: Duration = .seconds(20)

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            HStack {
                Text("Genaryx Bus")
                    .font(Theme.display(13, weight: .bold))
                    .foregroundStyle(Theme.textPrimary)
                Spacer()
                HStack(spacing: 6) {
                    Circle()
                        .fill(Theme.mint)
                        .frame(width: 6, height: 6)
                    Text("\(events.count)")
                        .font(Theme.mono(12, weight: .semibold))
                        .monospacedDigit()
                        .foregroundStyle(Theme.textSecondary)
                }
            }
            .padding(.horizontal, 12)
            .padding(.top, 12)

            MenuBarMoneySection(cloudModel: cloudModel)
                .padding(.horizontal, 12)
                .padding(.vertical, 10)

            Divider().overlay(Theme.hairline)

            ScrollView {
                VStack(alignment: .leading, spacing: 8) {
                    ForEach(events.prefix(Self.previewCount), id: \.rowKey) { event in
                        MenuBarEventLine(event: event)
                    }
                }
                .padding(12)
            }
            .frame(maxHeight: 300)

            Divider().overlay(Theme.hairline)

            HStack {
                Text(footerText)
                    .font(Theme.mono(10))
                    .foregroundStyle(Theme.textTertiary)
                    .lineLimit(1)
                    .truncationMode(.tail)
                Spacer()
                Button("Quit") {
                    NSApplication.shared.terminate(nil)
                }
                .buttonStyle(.plain)
                .font(Theme.mono(11, weight: .semibold))
                .foregroundStyle(Theme.textSecondary)
            }
            .padding(12)
        }
        .frame(width: 320)
        .background(Theme.background)
        .task(id: cloudModel.connection.isReady) {
            // Own refresh loop, independent of whether the Overview/Money
            // tabs happen to be the active tab in the main window right now
            // (their own `.task`s only run while THEY are on-screen) - runs
            // for as long as this popover is mounted, so opening the menu
            // bar alone is enough to keep the mini's burn readout live.
            guard cloudModel.connection.isReady else { return }
            while !Task.isCancelled {
                await cloudModel.refreshOverview()
                await cloudModel.refreshMoney()
                try? await Task.sleep(for: Self.refreshInterval)
            }
        }
    }

    private var footerText: String {
        if let unavailableMessage {
            return "core unavailable: \(unavailableMessage)"
        }
        return "live: genaryx-core via UniFFI"
    }
}

/// The popover's Money section: a compact burn readout (total spent, active
/// runs) plus a "Kill last runaway" break-glass action, both fed by the same
/// `CloudModel` the Overview/Money tabs read and mutate through. Kill is a
/// break-glass override exactly like the Money panel's own `RunsTable`
/// (Phase-2 wave 3B): arming it reveals the same shared `BreakGlassPanel`
/// ceremony (mandatory typed reason; Touch ID is challenged inside
/// `CloudModel.killRun` itself, so the mini never bypasses it) rather than
/// issuing its own Cloud call.
///
/// Fail-closed: any state short of `CloudConnection.ready`, or an empty/
/// not-yet-loaded runs list, shows an honest status line instead of a
/// number and disables the kill action - never a crash, never a silent
/// no-op.
@MainActor
private struct MenuBarMoneySection: View {
    let cloudModel: CloudModel

    @State private var killArmed = false

    var body: some View {
        VStack(alignment: .leading, spacing: 8) {
            statusLine
            killRow
            if killArmed, let target = lastRunaway {
                BreakGlassPanel(
                    summary: "Kill run \(target.runId) immediately.",
                    onConfirm: { reason in
                        _ = await cloudModel.killRun(target.runId, reason: reason)
                        killArmed = false
                    },
                    onCancel: { killArmed = false }
                )
            }
        }
    }

    @ViewBuilder
    private var statusLine: some View {
        switch cloudModel.connection {
        case .ready:
            if let overview = cloudModel.overview {
                HStack(spacing: 10) {
                    Text(MoneyFormat.usd(overview.totalSpentUsd))
                        .font(Theme.mono(15, weight: .semibold))
                        .monospacedDigit()
                        .foregroundStyle(Theme.textPrimary)
                    Text("\(overview.activeRuns) active")
                        .font(Theme.mono(11))
                        .foregroundStyle(Theme.textSecondary)
                    Spacer(minLength: 0)
                }
            } else {
                Text("loading money data...")
                    .font(Theme.mono(11))
                    .foregroundStyle(Theme.textTertiary)
            }
        case .connecting:
            Text("connecting to Cloud...")
                .font(Theme.mono(11))
                .foregroundStyle(Theme.textTertiary)
        case .noEnvironment:
            Text("no Cloud environment")
                .font(Theme.mono(11))
                .foregroundStyle(Theme.textTertiary)
        case .pairingFailed:
            Text("Cloud pairing failed")
                .font(Theme.mono(11))
                .foregroundStyle(Theme.coral)
        }
    }

    @ViewBuilder
    private var killRow: some View {
        if let target = lastRunaway {
            VStack(alignment: .leading, spacing: 6) {
                HStack(spacing: 8) {
                    VStack(alignment: .leading, spacing: 1) {
                        Text("last runaway")
                            .font(Theme.mono(9, weight: .semibold))
                            .tracking(0.8)
                            .foregroundStyle(Theme.textTertiary)
                        Text(target.runId)
                            .font(Theme.mono(11))
                            .foregroundStyle(Theme.textSecondary)
                            .lineLimit(1)
                            .truncationMode(.middle)
                            .help(target.runId)
                    }
                    Spacer(minLength: 8)
                    Text(MoneyFormat.usd(target.spentUsd))
                        .font(Theme.mono(12, weight: .semibold))
                        .monospacedDigit()
                        .foregroundStyle(Theme.textPrimary)
                }
                if !killArmed {
                    Button {
                        killArmed = true
                    } label: {
                        HStack(spacing: 4) {
                            Image(systemName: "exclamationmark.triangle.fill")
                                .font(.system(size: 8, weight: .bold))
                            Text("Kill last runaway")
                        }
                        .font(Theme.mono(11, weight: .semibold))
                        .foregroundStyle(Theme.ember)
                    }
                    .buttonStyle(.plain)
                }
            }
        } else {
            Text(cloudModel.connection.isReady ? "no active runs" : "kill unavailable")
                .font(Theme.mono(11))
                .foregroundStyle(Theme.textTertiary)
        }
    }

    /// The non-killed run with the highest `spentUsd`, out of `CloudModel`'s
    /// own `runs` - the same list `MoneyView`'s `RunsTable` shows, so "last
    /// runaway" always names the same run in both the Money panel and the
    /// menu-bar mini.
    private var lastRunaway: Run? {
        cloudModel.runs.filter { !$0.killed }.max { $0.spentUsd < $1.spentUsd }
    }
}

/// One condensed row in the menu-bar quick view: severity dot, source, type.
@MainActor
private struct MenuBarEventLine: View {
    let event: UiEvent

    var body: some View {
        HStack(spacing: 8) {
            Circle()
                .fill(Theme.severityColor(event.severity))
                .frame(width: 6, height: 6)
            Text(event.source)
                .font(Theme.mono(10, weight: .semibold))
                .foregroundStyle(Theme.sourceColor(event.source))
                .frame(width: 64, alignment: .leading)
                .lineLimit(1)
            Text(event.eventType)
                .font(Theme.mono(11))
                .foregroundStyle(Theme.textPrimary)
                .lineLimit(1)
                .truncationMode(.tail)
            Spacer(minLength: 0)
        }
    }
}
