import AppKit
import GenaryxCoreFFI
import SwiftUI

/// Genaryx: the native macOS SwiftUI shell (decision D2) over `genaryx-core`.
///
/// `FleetModel` constructs the real `FleetHandle` through the UniFFI bridge
/// (`GenaryxCoreFFI`, generated by `build-ffi.sh` from `crates/ffi`) and
/// feeds both the main window and the menu-bar view from one live,
/// appending event stream, replacing the Phase-0 `MockData` array.
///
/// Phase-1 wave 3 (docs/PHASE1.md) adds `CloudModel`, the same kind of
/// UniFFI-backed live model but over `CloudHandle` (`crates/ffi/src/cloud`)
/// instead of `FleetHandle`, feeding the new Overview and Money panels
/// alongside the existing Bus Explorer via `TabBar` below - at parity with
/// the Tauri shell's three-view `AppHeader.tsx`/`AppShell.tsx` switcher.
@main
struct GenaryxApp: App {
    @State private var model = FleetModel()
    @State private var cloudModel = CloudModel()
    @State private var tab: AppTab = .overview

    var body: some Scene {
        WindowGroup("Genaryx") {
            VStack(spacing: 0) {
                TabBar(tab: $tab)
                Divider().overlay(Theme.hairline)
                Group {
                    switch tab {
                    case .overview:
                        OverviewView(model: cloudModel)
                    case .money:
                        MoneyView(model: cloudModel)
                    case .bus:
                        VStack(spacing: 0) {
                            if let message = model.unavailableMessage {
                                CoreUnavailableBanner(message: message)
                            }
                            BusExplorerView(events: model.events)
                        }
                    }
                }
            }
            .frame(minWidth: 900, minHeight: 600)
        }

        MenuBarExtra {
            MenuBarBusView(events: model.events, unavailableMessage: model.unavailableMessage)
        } label: {
            MenuBarLabel(count: model.events.count)
        }
        .menuBarExtraStyle(.window)
    }
}

/// The three top-level nav destinations - Overview, Money, and the existing
/// Bus Explorer - matching the Tauri shell's `ViewId`/`lib/views.ts` three-
/// tab switcher, rendered as a native macOS tab strip instead of a
/// web-styled nav bar (native macOS patterns over pixel parity, same rule
/// `Theme.swift` already follows).
private enum AppTab: String, CaseIterable, Identifiable {
    case overview = "Overview"
    case money = "Money"
    case bus = "Bus Explorer"

    var id: String { rawValue }
}

/// Persistent app chrome above whichever tab is active: brand mark plus the
/// view switcher. Mirrors `AppHeader.tsx`'s role (shown once regardless of
/// which view is active) without reproducing its web-specific theme toggle
/// (this shell already follows the system light/dark appearance - see
/// `Color.dynamic` in `Theme.swift`).
@MainActor
private struct TabBar: View {
    @Binding var tab: AppTab

    var body: some View {
        HStack(spacing: 14) {
            HStack(spacing: 8) {
                Image(systemName: "bolt.fill")
                    .font(.system(size: 13, weight: .bold))
                    .foregroundStyle(Theme.amber)
                VStack(alignment: .leading, spacing: 1) {
                    Text("Genaryx")
                        .font(Theme.display(13, weight: .bold))
                        .foregroundStyle(Theme.textPrimary)
                    Text("CONTROL ROOM")
                        .font(Theme.mono(9, weight: .semibold))
                        .tracking(1.4)
                        .foregroundStyle(Theme.textTertiary)
                }
            }

            HStack(spacing: 2) {
                ForEach(AppTab.allCases) { item in
                    Button {
                        tab = item
                    } label: {
                        Text(item.rawValue)
                            .font(Theme.mono(11.5, weight: .semibold))
                            .foregroundStyle(tab == item ? Theme.textPrimary : Theme.textSecondary)
                            .padding(.horizontal, 12)
                            .padding(.vertical, 6)
                            .background(
                                RoundedRectangle(cornerRadius: 8, style: .continuous)
                                    .fill(tab == item ? Theme.panelElevated : Color.clear)
                            )
                            .overlay(
                                RoundedRectangle(cornerRadius: 8, style: .continuous)
                                    .strokeBorder(tab == item ? Theme.hairlineStrong : Color.clear, lineWidth: 1)
                            )
                    }
                    .buttonStyle(.plain)
                }
            }
            .padding(.leading, 4)

            Spacer(minLength: 0)
        }
        .padding(.horizontal, 16)
        .padding(.vertical, 10)
        .background(Theme.panel)
    }
}

/// Shown above the Bus Explorer only when `FleetHandle()` failed to
/// construct. Fail-closed: the shell still launches and renders (with an
/// empty list) instead of crashing.
@MainActor
private struct CoreUnavailableBanner: View {
    let message: String

    var body: some View {
        HStack(spacing: 8) {
            Image(systemName: "exclamationmark.triangle.fill")
                .foregroundStyle(Theme.ember)
            Text("Core unavailable: \(message)")
                .font(Theme.mono(11, weight: .semibold))
                .foregroundStyle(Theme.textSecondary)
                .lineLimit(1)
                .truncationMode(.tail)
            Spacer(minLength: 0)
        }
        .padding(.horizontal, 16)
        .padding(.vertical, 8)
        .background(Theme.panelElevated)
    }
}

/// The `NSStatusItem` label: a small glyph plus the live event count, kept
/// terse since the status bar has very little horizontal room.
@MainActor
private struct MenuBarLabel: View {
    let count: Int

    var body: some View {
        Label {
            Text("\(count)")
                .monospacedDigit()
        } icon: {
            Image(systemName: "waveform.path.ecg")
        }
    }
}

/// The MenuBarExtra's popover content: a condensed, read-only slice of the
/// bus feed, so a quick glance never requires opening the main window.
@MainActor
private struct MenuBarBusView: View {
    let events: [UiEvent]
    let unavailableMessage: String?

    private static let previewCount = 8

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            HStack {
                Text("Genaryx Bus")
                    .font(Theme.display(13, weight: .bold))
                    .foregroundStyle(Theme.textPrimary)
                Spacer()
                HStack(spacing: 6) {
                    Circle()
                        .fill(Theme.mint)
                        .frame(width: 6, height: 6)
                    Text("\(events.count)")
                        .font(Theme.mono(12, weight: .semibold))
                        .monospacedDigit()
                        .foregroundStyle(Theme.textSecondary)
                }
            }
            .padding(12)

            Divider().overlay(Theme.hairline)

            ScrollView {
                VStack(alignment: .leading, spacing: 8) {
                    ForEach(events.prefix(Self.previewCount), id: \.rowKey) { event in
                        MenuBarEventLine(event: event)
                    }
                }
                .padding(12)
            }
            .frame(maxHeight: 300)

            Divider().overlay(Theme.hairline)

            HStack {
                Text(footerText)
                    .font(Theme.mono(10))
                    .foregroundStyle(Theme.textTertiary)
                    .lineLimit(1)
                    .truncationMode(.tail)
                Spacer()
                Button("Quit") {
                    NSApplication.shared.terminate(nil)
                }
                .buttonStyle(.plain)
                .font(Theme.mono(11, weight: .semibold))
                .foregroundStyle(Theme.textSecondary)
            }
            .padding(12)
        }
        .frame(width: 320)
        .background(Theme.background)
    }

    private var footerText: String {
        if let unavailableMessage {
            return "core unavailable: \(unavailableMessage)"
        }
        return "live: genaryx-core via UniFFI"
    }
}

/// One condensed row in the menu-bar quick view: severity dot, source, type.
@MainActor
private struct MenuBarEventLine: View {
    let event: UiEvent

    var body: some View {
        HStack(spacing: 8) {
            Circle()
                .fill(Theme.severityColor(event.severity))
                .frame(width: 6, height: 6)
            Text(event.source)
                .font(Theme.mono(10, weight: .semibold))
                .foregroundStyle(Theme.sourceColor(event.source))
                .frame(width: 64, alignment: .leading)
                .lineLimit(1)
            Text(event.eventType)
                .font(Theme.mono(11))
                .foregroundStyle(Theme.textPrimary)
                .lineLimit(1)
                .truncationMode(.tail)
            Spacer(minLength: 0)
        }
    }
}
