import AppKit
import GenaryxCoreFFI
import SwiftUI

/// Genaryx: the native macOS SwiftUI shell (decision D2) over `genaryx-core`.
///
/// `FleetModel` constructs the real `FleetHandle` through the UniFFI bridge
/// (`GenaryxCoreFFI`, generated by `build-ffi.sh` from `crates/ffi`) and
/// feeds both the main window and the menu-bar view from one live,
/// appending event stream, replacing the Phase-0 `MockData` array.
///
/// Phase-1 wave 3 (docs/PHASE1.md) adds `CloudModel`, the same kind of
/// UniFFI-backed live model but over `CloudHandle` (`crates/ffi/src/cloud`)
/// instead of `FleetHandle`, feeding the new Overview and Money panels
/// alongside the existing Bus Explorer via `TabBar` below - at parity with
/// the Tauri shell's three-view `AppHeader.tsx`/`AppShell.tsx` switcher.
///
/// Phase-2 wave 2 (docs/PHASE2.md) adds `PolicyModel`, the same kind of
/// UniFFI-backed live model but over `WardryxHandle`
/// (`crates/ffi/src/wardryx`), feeding the new Policy panel (Decision
/// Stream, Approvals Inbox, Policy view). Its Decision Stream section reads
/// `model.events` (the existing `FleetModel` bus feed) directly, filtered to
/// `source == "wardryx"` - PHASE2.md: "NOT a new REST read" - so `PolicyView`
/// is handed `model.events` alongside its own `policyModel`.
@main
struct GenaryxApp: App {
    @State private var model = FleetModel()
    @State private var cloudModel = CloudModel()
    @State private var policyModel = PolicyModel()
    @State private var tab: AppTab = .overview

    var body: some Scene {
        WindowGroup("Genaryx") {
            VStack(spacing: 0) {
                TabBar(tab: $tab)
                Divider().overlay(Theme.hairline)
                Group {
                    switch tab {
                    case .overview:
                        OverviewView(model: cloudModel)
                    case .money:
                        MoneyView(model: cloudModel)
                    case .policy:
                        PolicyView(model: policyModel, busEvents: model.events)
                    case .bus:
                        VStack(spacing: 0) {
                            if let message = model.unavailableMessage {
                                CoreUnavailableBanner(message: message)
                            }
                            BusExplorerView(events: model.events)
                        }
                    }
                }
            }
            .frame(minWidth: 900, minHeight: 600)
        }

        MenuBarExtra {
            MenuBarBusView(events: model.events, unavailableMessage: model.unavailableMessage, cloudModel: cloudModel)
        } label: {
            MenuBarLabel(count: model.events.count, cloudModel: cloudModel)
        }
        .menuBarExtraStyle(.window)
    }
}

/// The four top-level nav destinations - Overview, Money, Policy, and the
/// existing Bus Explorer - matching the Tauri shell's `ViewId`/`lib/views.ts`
/// switcher (now four-way as of Phase-2 wave 2's Policy panel), rendered as
/// a native macOS tab strip instead of a web-styled nav bar (native macOS
/// patterns over pixel parity, same rule `Theme.swift` already follows).
private enum AppTab: String, CaseIterable, Identifiable {
    case overview = "Overview"
    case money = "Money"
    case policy = "Policy"
    case bus = "Bus Explorer"

    var id: String { rawValue }
}

/// Persistent app chrome above whichever tab is active: brand mark plus the
/// view switcher. Mirrors `AppHeader.tsx`'s role (shown once regardless of
/// which view is active) without reproducing its web-specific theme toggle
/// (this shell already follows the system light/dark appearance - see
/// `Color.dynamic` in `Theme.swift`).
@MainActor
private struct TabBar: View {
    @Binding var tab: AppTab

    var body: some View {
        HStack(spacing: 14) {
            HStack(spacing: 8) {
                Image(systemName: "bolt.fill")
                    .font(.system(size: 13, weight: .bold))
                    .foregroundStyle(Theme.amber)
                VStack(alignment: .leading, spacing: 1) {
                    Text("Genaryx")
                        .font(Theme.display(13, weight: .bold))
                        .foregroundStyle(Theme.textPrimary)
                    Text("CONTROL ROOM")
                        .font(Theme.mono(9, weight: .semibold))
                        .tracking(1.4)
                        .foregroundStyle(Theme.textTertiary)
                }
            }

            HStack(spacing: 2) {
                ForEach(AppTab.allCases) { item in
                    Button {
                        tab = item
                    } label: {
                        Text(item.rawValue)
                            .font(Theme.mono(11.5, weight: .semibold))
                            .foregroundStyle(tab == item ? Theme.textPrimary : Theme.textSecondary)
                            .padding(.horizontal, 12)
                            .padding(.vertical, 6)
                            .background(
                                RoundedRectangle(cornerRadius: 8, style: .continuous)
                                    .fill(tab == item ? Theme.panelElevated : Color.clear)
                            )
                            .overlay(
                                RoundedRectangle(cornerRadius: 8, style: .continuous)
                                    .strokeBorder(tab == item ? Theme.hairlineStrong : Color.clear, lineWidth: 1)
                            )
                    }
                    .buttonStyle(.plain)
                }
            }
            .padding(.leading, 4)

            Spacer(minLength: 0)
        }
        .padding(.horizontal, 16)
        .padding(.vertical, 10)
        .background(Theme.panel)
    }
}

/// Shown above the Bus Explorer only when `FleetHandle()` failed to
/// construct. Fail-closed: the shell still launches and renders (with an
/// empty list) instead of crashing.
@MainActor
private struct CoreUnavailableBanner: View {
    let message: String

    var body: some View {
        HStack(spacing: 8) {
            Image(systemName: "exclamationmark.triangle.fill")
                .foregroundStyle(Theme.ember)
            Text("Core unavailable: \(message)")
                .font(Theme.mono(11, weight: .semibold))
                .foregroundStyle(Theme.textSecondary)
                .lineLimit(1)
                .truncationMode(.tail)
            Spacer(minLength: 0)
        }
        .padding(.horizontal, 16)
        .padding(.vertical, 8)
        .background(Theme.panelElevated)
    }
}

/// The `NSStatusItem` label: a small glyph plus the live event count (kept
/// exactly as before - terse, since the status bar has very little
/// horizontal room), plus a compact burn figure from `CloudModel` (Phase-1
/// wave 5, docs/PHASE1.md; 08 §2, 09 Ф1 upstream) alongside it.
@MainActor
private struct MenuBarLabel: View {
    let count: Int
    let cloudModel: CloudModel

    var body: some View {
        HStack(spacing: 6) {
            Label {
                Text("\(count)")
                    .monospacedDigit()
            } icon: {
                Image(systemName: "waveform.path.ecg")
            }
            if let burnText {
                Text(burnText)
                    .monospacedDigit()
            }
        }
    }

    /// `nil` until `CloudModel` has a real reading (still connecting, no
    /// environment, pairing failed), so the always-visible status item never
    /// shows a fabricated or stale-looking number - fail-closed: absent
    /// beats wrong. Once `CloudModel.overview` has a value, this keeps
    /// showing it even through a later transient refresh error, the same
    /// "last known good over blank" posture `MoneyView`/`OverviewView`
    /// already take with their own `model.overview`/`model.runs`.
    private var burnText: String? {
        guard let overview = cloudModel.overview else { return nil }
        return MoneyFormat.usd(overview.totalSpentUsd)
    }
}

/// The MenuBarExtra's popover content: a condensed, read-only slice of the
/// bus feed, so a quick glance never requires opening the main window - plus
/// (Phase-1 wave 5) the Money section right below the header: a burn
/// readout and a "kill last runaway" action over the same `CloudModel` the
/// Overview/Money tabs use, so the mini never issues its own Cloud calls.
@MainActor
private struct MenuBarBusView: View {
    let events: [UiEvent]
    let unavailableMessage: String?
    let cloudModel: CloudModel

    private static let previewCount = 8
    /// Matches `OverviewView`/`MoneyView`'s own refresh cadence, so the mini
    /// never looks "more live" or "more stale" than the panel it mirrors.
    private static let refreshInterval: Duration = .seconds(20)

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            HStack {
                Text("Genaryx Bus")
                    .font(Theme.display(13, weight: .bold))
                    .foregroundStyle(Theme.textPrimary)
                Spacer()
                HStack(spacing: 6) {
                    Circle()
                        .fill(Theme.mint)
                        .frame(width: 6, height: 6)
                    Text("\(events.count)")
                        .font(Theme.mono(12, weight: .semibold))
                        .monospacedDigit()
                        .foregroundStyle(Theme.textSecondary)
                }
            }
            .padding(.horizontal, 12)
            .padding(.top, 12)

            MenuBarMoneySection(cloudModel: cloudModel)
                .padding(.horizontal, 12)
                .padding(.vertical, 10)

            Divider().overlay(Theme.hairline)

            ScrollView {
                VStack(alignment: .leading, spacing: 8) {
                    ForEach(events.prefix(Self.previewCount), id: \.rowKey) { event in
                        MenuBarEventLine(event: event)
                    }
                }
                .padding(12)
            }
            .frame(maxHeight: 300)

            Divider().overlay(Theme.hairline)

            HStack {
                Text(footerText)
                    .font(Theme.mono(10))
                    .foregroundStyle(Theme.textTertiary)
                    .lineLimit(1)
                    .truncationMode(.tail)
                Spacer()
                Button("Quit") {
                    NSApplication.shared.terminate(nil)
                }
                .buttonStyle(.plain)
                .font(Theme.mono(11, weight: .semibold))
                .foregroundStyle(Theme.textSecondary)
            }
            .padding(12)
        }
        .frame(width: 320)
        .background(Theme.background)
        .task(id: cloudModel.connection.isReady) {
            // Own refresh loop, independent of whether the Overview/Money
            // tabs happen to be the active tab in the main window right now
            // (their own `.task`s only run while THEY are on-screen) - runs
            // for as long as this popover is mounted, so opening the menu
            // bar alone is enough to keep the mini's burn readout live.
            guard cloudModel.connection.isReady else { return }
            while !Task.isCancelled {
                await cloudModel.refreshOverview()
                await cloudModel.refreshMoney()
                try? await Task.sleep(for: Self.refreshInterval)
            }
        }
    }

    private var footerText: String {
        if let unavailableMessage {
            return "core unavailable: \(unavailableMessage)"
        }
        return "live: genaryx-core via UniFFI"
    }
}

/// The popover's Money section: a compact burn readout (total spent, active
/// runs) plus a "Kill last runaway" action, both fed by the same
/// `CloudModel` the Overview/Money tabs read and mutate through.
///
/// Fail-closed: any state short of `CloudConnection.ready`, or an empty/
/// not-yet-loaded runs list, shows an honest status line instead of a
/// number and disables the kill action - never a crash, never a silent
/// no-op.
@MainActor
private struct MenuBarMoneySection: View {
    let cloudModel: CloudModel

    var body: some View {
        VStack(alignment: .leading, spacing: 8) {
            statusLine
            killRow
        }
    }

    @ViewBuilder
    private var statusLine: some View {
        switch cloudModel.connection {
        case .ready:
            if let overview = cloudModel.overview {
                HStack(spacing: 10) {
                    Text(MoneyFormat.usd(overview.totalSpentUsd))
                        .font(Theme.mono(15, weight: .semibold))
                        .monospacedDigit()
                        .foregroundStyle(Theme.textPrimary)
                    Text("\(overview.activeRuns) active")
                        .font(Theme.mono(11))
                        .foregroundStyle(Theme.textSecondary)
                    Spacer(minLength: 0)
                }
            } else {
                Text("loading money data...")
                    .font(Theme.mono(11))
                    .foregroundStyle(Theme.textTertiary)
            }
        case .connecting:
            Text("connecting to Cloud...")
                .font(Theme.mono(11))
                .foregroundStyle(Theme.textTertiary)
        case .noEnvironment:
            Text("no Cloud environment")
                .font(Theme.mono(11))
                .foregroundStyle(Theme.textTertiary)
        case .pairingFailed:
            Text("Cloud pairing failed")
                .font(Theme.mono(11))
                .foregroundStyle(Theme.coral)
        }
    }

    @ViewBuilder
    private var killRow: some View {
        if let target = lastRunaway {
            VStack(alignment: .leading, spacing: 6) {
                HStack(spacing: 8) {
                    VStack(alignment: .leading, spacing: 1) {
                        Text("last runaway")
                            .font(Theme.mono(9, weight: .semibold))
                            .tracking(0.8)
                            .foregroundStyle(Theme.textTertiary)
                        Text(target.runId)
                            .font(Theme.mono(11))
                            .foregroundStyle(Theme.textSecondary)
                            .lineLimit(1)
                            .truncationMode(.middle)
                            .help(target.runId)
                    }
                    Spacer(minLength: 8)
                    Text(MoneyFormat.usd(target.spentUsd))
                        .font(Theme.mono(12, weight: .semibold))
                        .monospacedDigit()
                        .foregroundStyle(Theme.textPrimary)
                }
                ConfirmButton(
                    label: "Kill last runaway",
                    confirmLabel: "Confirm kill",
                    tone: Theme.ember,
                    onConfirm: { _ = await cloudModel.killRun(target.runId) }
                )
            }
        } else {
            Text(cloudModel.connection.isReady ? "no active runs" : "kill unavailable")
                .font(Theme.mono(11))
                .foregroundStyle(Theme.textTertiary)
        }
    }

    /// The non-killed run with the highest `spentUsd`, out of `CloudModel`'s
    /// own `runs` - the same list `MoneyView`'s `RunsTable` shows, so "last
    /// runaway" always names the same run in both the Money panel and the
    /// menu-bar mini.
    private var lastRunaway: Run? {
        cloudModel.runs.filter { !$0.killed }.max { $0.spentUsd < $1.spentUsd }
    }
}

/// One condensed row in the menu-bar quick view: severity dot, source, type.
@MainActor
private struct MenuBarEventLine: View {
    let event: UiEvent

    var body: some View {
        HStack(spacing: 8) {
            Circle()
                .fill(Theme.severityColor(event.severity))
                .frame(width: 6, height: 6)
            Text(event.source)
                .font(Theme.mono(10, weight: .semibold))
                .foregroundStyle(Theme.sourceColor(event.source))
                .frame(width: 64, alignment: .leading)
                .lineLimit(1)
            Text(event.eventType)
                .font(Theme.mono(11))
                .foregroundStyle(Theme.textPrimary)
                .lineLimit(1)
                .truncationMode(.tail)
            Spacer(minLength: 0)
        }
    }
}
